name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
      - run: |
          CGO_ENABLED=0 GOOS=darwin GOARCH=arm64 go build -ldflags="-w -s" -o distribution_darwin_arm64 main.go

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: distribution_darwin_arm64
